# Generated by Django 3.1.3 on 2021-10-02 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='ValueAtWhichBought',
            new_name='totalExpenditure',
        ),
    ]
