# Generated by Django 3.2.3 on 2021-10-03 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20211002_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='Transaction_By', serialize=False, to='backend.user')),
                ('intialQuantity', models.IntegerField(default=0)),
                ('finalQuantity', models.IntegerField(default=0)),
                ('stockQuote', models.CharField(default='stock', max_length=100)),
                ('priceAtWhichBought', models.IntegerField(default=0)),
                ('priceAtWhichSold', models.IntegerField(default=0)),
                ('intialCredits', models.IntegerField(default=0)),
                ('finalCredits', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Transaction History',
                'db_table': 'Transaction_History',
            },
        ),
        migrations.RemoveField(
            model_name='stock',
            name='value',
        ),
    ]
